services:
  back-end:
    build:
      context: .
      dockerfile: back-end/Dockerfile
    image: softy-pinko-back-end:task4
    container_name: softy-pinko-back-end
    ports:
      - "5252:5252"

  front-end:
    build:
      context: .
      dockerfile: front-end/Dockerfile
    image: softy-pinko-front-end:task4
    container_name: softy-pinko-front-end
    ports:
      - "9000:9000"
    depends_on:
      - back-end
