# Utiliser l’image Ubuntu la plus récente comme base
FROM ubuntu:latest

# Mettre à jour le gestionnaire de paquets
RUN apt-get update

# Mettre à jour les paquets installés
RUN apt-get upgrade -y

# Définir la commande à exécuter lors du lancement du conteneur
CMD echo "Hello, World!"
